In [9]:
import gymnasium as gym
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
df=pd.read_csv('Ads_Clicks.csv')
df

      Ad 1  Ad 2  Ad 3  Ad 4  Ad 5  Ad 6  Ad 7  Ad 8  Ad 9  Ad 10
0        1     0     0     0     1     0     0     0     1      0
1        0     0     0     0     0     0     0     0     1      0
2        0     0     0     0     0     0     0     0     0      0
3        0     1     0     0     0     0     0     1     0      0
4        0     0     0     0     0     0     0     0     0      0
...    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
9995     0     0     1     0     0     0     0     1     0      0
9996     0     0     0     0     0     0     0     0     0      0
9997     0     0     0     0     0     0     0     0     0      0
9998     1     0     0     0     0     0     0     1     0      0
9999     0     1     0     0     0     0     0     0     0      0

[10000 rows x 10 columns]

In [11]:
import numpy as np

def epsilon_greedy(rewards, epsilon):
    num_ads = len(rewards)
    if np.random.random() < epsilon:

        return np.random.choice(num_ads)
    else:

        return np.argmax(rewards)


def compute_total_rewards(epsilon):

    num_ads = 10
    rewards = np.zeros(num_ads)
    total_rewards = 0


    for _ in range(2000):

        chosen_ad = epsilon_greedy(rewards, epsilon)

        reward = np.random.choice([0, 1])

        total_rewards += reward

        rewards[chosen_ad] = (rewards[chosen_ad] * (_ + 1) + reward) / (_ + 2)

    return total_rewards


total_rewards_epsilon_001 = compute_total_rewards(0.01)
total_rewards_epsilon_03 = compute_total_rewards(0.3)

print("Total rewards for ε=0.01:", total_rewards_epsilon_001)
print("Total rewards for ε=0.3:", total_rewards_epsilon_03)

Total rewards for ε=0.01: 970
Total rewards for ε=0.3: 983

In [12]:
import numpy as np


def compute_ucb(rewards, counts, total_counts, c):
    num_ads = len(rewards)
    ucb_values = np.zeros(num_ads)
    for ad in range(num_ads):
        if counts[ad] == 0:
            ucb_values[ad] = float('inf')
        else:
            ucb_values[ad] = rewards[ad] + c * np.sqrt(np.log(total_counts) / counts[ad])
    return ucb_values


def choose_arm_ucb(ucb_values):
    return np.argmax(ucb_values)


def compute_total_rewards_ucb(c):

    num_ads = 10
    rewards = np.zeros(num_ads)
    counts = np.zeros(num_ads)
    total_rewards = 0

    for t in range(2000):

        ucb_values = compute_ucb(rewards, counts, t + 1, c)

        chosen_ad = choose_arm_ucb(ucb_values)

        reward = np.random.choice([0, 1])

        total_rewards += reward

        counts[chosen_ad] += 1
        rewards[chosen_ad] = ((counts[chosen_ad] - 1) * rewards[chosen_ad] + reward) / counts[chosen_ad]

    return total_rewards

# Compute total rewards for c = 1.5
total_rewards_ucb = compute_total_rewards_ucb(1.5)
print("Total rewards using UCB with c=1.5:", total_rewards_ucb)

Total rewards using UCB with c=1.5: 937